# Generated by Django 5.0 on 2023-12-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedata',
            name='embedded_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='time_slot_1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='time_slot_2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='time_slot_3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='templedata',
            name='embedded_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templedata',
            name='time_slot_1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='templedata',
            name='time_slot_2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='templedata',
            name='time_slot_3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
