# Generated by Django 5.0 on 2023-12-29 00:52

import cms.temples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_servicedata_embedded_url_servicedata_time_slot_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedata',
            name='service_areas',
            field=models.JSONField(blank=True, default=cms.temples.models.default_blank_fields, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='social_media',
            field=models.JSONField(blank=True, default=cms.temples.models.default_blank_fields, null=True),
        ),
        migrations.AddField(
            model_name='templedata',
            name='social_media',
            field=models.JSONField(blank=True, default=cms.temples.models.default_blank_fields, null=True),
        ),
    ]
