# Generated by Django 5.0 on 2023-12-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_servicedata_service_areas_servicedata_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegallery',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='templegallery',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
