# Generated by Django 5.0 on 2023-12-25 11:33

import adminapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('package', models.CharField(choices=[('1', 'Basic'), ('2', 'Advanced'), ('3', 'Premium'), ('4', 'Enterprise'), ('5', 'Other')], max_length=80, null=True)),
                ('portal_type', models.CharField(choices=[('1', 'BLOG'), ('2', 'LISTING'), ('3', 'DATA'), ('4', 'CRM'), ('5', 'ERP')], max_length=80, null=True, unique=True)),
                ('user_limit', models.IntegerField(blank=True, null=True)),
                ('criterion_limit', models.IntegerField(blank=True, null=True)),
                ('data_limit', models.IntegerField(blank=True, null=True)),
                ('file_size_limit', models.IntegerField(blank=True, null=True)),
                ('other_limit', models.IntegerField(blank=True, null=True)),
                ('admin_pin', models.IntegerField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(default=1, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('tags', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('input_version', models.CharField(blank=True, choices=[('1', '2020'), ('2', '2021'), ('3', '2022'), ('4', '2023'), ('5', '2024'), ('6', '2025')], max_length=20, null=True, unique=True)),
                ('report_version', models.CharField(blank=True, choices=[('1', '2020'), ('2', '2021'), ('3', '2022'), ('4', '2023'), ('5', '2024'), ('6', '2025')], max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allow_signup', models.BooleanField(blank=True, default=True)),
                ('allow_data_entry', models.BooleanField(blank=True, default=True)),
                ('allow_change_roles', models.BooleanField(blank=True, default=True)),
                ('enable_otp', models.BooleanField(blank=True, default=False)),
                ('enable_captha', models.BooleanField(blank=True, default=False)),
                ('enable_https', models.BooleanField(blank=True, default=False)),
                ('other', models.BooleanField(blank=True, default=True)),
                ('classic_ui', models.BooleanField(blank=True, default=False)),
                ('is_app_active', models.BooleanField(default=True, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('admin_url', models.URLField(blank=True, null=True)),
                ('admin_address', models.CharField(blank=True, max_length=225, null=True)),
                ('jdoc', models.JSONField(blank=True, default=adminapp.models.default_blank_fields, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('id_no', models.IntegerField(null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=adminapp.models.admin_file_upload_directory_path)),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to=adminapp.models.admin_file_upload_directory_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=adminapp.models.admin_file_upload_directory_path)),
                ('files', models.FileField(blank=True, null=True, upload_to=adminapp.models.admin_file_upload_directory_path)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('package_id', models.CharField(choices=[('1', 'Basic'), ('2', 'Advanced'), ('3', 'Premium'), ('4', 'Enterprise'), ('5', 'Other')], max_length=80, null=True)),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('id_no', models.IntegerField(null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('TOS', 'Terms Of Service'), ('PRIVACY', 'Privacy policy'), ('OTHER', 'Other'), ('DATA', 'Data Policy'), ('BILLING', 'Billing and Finance')], default='TOS', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
