# Generated by Django 5.0 on 2023-12-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.RenameField(
            model_name='adminconfig',
            old_name='criterion_limit',
            new_name='page_limit',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='input_version',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='report_version',
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='useragreements',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useragreements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
