# Generated by Django 5.0 on 2023-12-25 11:33

import features.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=12, null=True)),
                ('code', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('package', models.CharField(choices=[('1', 'Basic'), ('2', 'Advanced'), ('3', 'Premium'), ('4', 'Enterprise'), ('5', 'Other')], max_length=220, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('is_paid', models.BooleanField(blank=True, default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=225, null=True)),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('ad_content', models.TextField(blank=True, null=True)),
                ('ad_image', models.FileField(blank=True, null=True, upload_to=features.models.get_upload_directory_path)),
                ('ad_url', models.URLField(blank=True, null=True)),
                ('ad_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=12, null=True)),
                ('batch_no', models.IntegerField(blank=True, unique=True)),
                ('established_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('established_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('established_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('faq_no', models.IntegerField(null=True, unique=True)),
                ('question', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('tags', models.CharField(blank=True, max_length=220, null=True, unique=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('jdoc', models.JSONField(blank=True, default=features.models.default_blank_fields, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=features.models.get_upload_directory_path)),
                ('files', models.FileField(blank=True, null=True, upload_to=features.models.get_upload_directory_path)),
                ('urls', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('id_no', models.IntegerField(null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('jdoc', models.JSONField(blank=True, default=features.models.default_blank_fields, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=features.models.get_upload_directory_path)),
                ('urls', models.URLField(blank=True, null=True)),
                ('link_to', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('user_uuid', models.UUIDField(blank=True, null=True)),
                ('user_ref', models.CharField(max_length=120, null=True)),
                ('code', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('txn_from', models.CharField(choices=[('1', 'Customer'), ('2', 'System'), ('3', 'User')], max_length=220, null=True)),
                ('txn_to', models.CharField(choices=[('1', 'Customer'), ('2', 'System'), ('3', 'User')], max_length=220, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('is_paid', models.BooleanField(blank=True, default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=225, null=True)),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=120, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=40, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
