# Generated by Django 5.0 on 2023-12-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
