# Generated by Django 5.0 on 2023-12-25 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter a valid email address.', max_length=254, null=True, unique=True)),
                ('username', models.CharField(help_text='Enter your Phone number.', max_length=30, unique=True, verbose_name='User ID')),
                ('department_id', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('designation', models.CharField(blank=True, choices=[('1', 'Pujari or Priest'), ('2', 'Archaka or Kazhakam'), ('3', 'Sthapati'), ('4', 'Astrologer'), ('5', 'Administrative Staff'), ('6', 'Tantric'), ('7', 'Artists'), ('8', 'Cook'), ('9', 'Hereditary'), ('10', 'Volunteers')], max_length=100, null=True)),
                ('user_scope', models.CharField(choices=[('1', 'Super Admin'), ('2', 'Portal Admin'), ('3', 'Portal Manager'), ('4', 'Project Coordinator'), ('5', 'Premium User'), ('6', 'Normal User'), ('7', 'Clubs'), ('8', 'Customer'), ('9', 'Other')], default='6', max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Mobile number')),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('referred_by', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(blank=True, default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('points', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('from_user', models.CharField(blank=True, max_length=120, null=True)),
                ('code', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('txn_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=25, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
