# Generated by Django 5.0 on 2023-12-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='logs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='txn_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
